name: Windows CI
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git mingw-w64-x86_64-cc
      - name: Install Deno
        uses: denoland/setup-deno@1
        with:
          deno-version: 1.19

      - name: Run the formatter
        run: |
          shopt -s globstar failglob
          deno fmt --check
      - name: Build SQLite
        id: build
        run: |
          export DENO_INSTALL="/home/runner/.deno"
          export PATH="$DENO_INSTALL/bin:$PATH"
          pacman -S --noconfirm tclsh brotli
          cd build
          make setup amalgamation release
      - name: Set Timezone to Non-UTC
        uses: zcong1993/setup-timezone@1
        with:
          timezon: America/New_York
      - name: Generate Test Database
        run: |
          cd build
          make testdb
      - name: Remove any non tracked build artifacts
        run: |
          cd build
          make clean
      - name: Run tests
        run: deno test --allow-read --allow-write test.ts
      - name: Run tests (unstable)
        run: deno test --unstable --allow-read --allow-write test.ts
      - name: Run benchmarks
        run: deno run bench.ts
